Sprint 2
sokol-rc/middle.messenger.praktikum.yandex pull request #6
Opened 2022-10-06 09:43 UTC by sokol-rc

2022-10-06 13:19 UTC, agadoev requested changes
Привет, @sokol-rc 
Спасибо за работу. Я не очень понял идею с разделением пропсов на IncomingProps и Props, но иногда ответственности действительно лучше разделять и если за этим есть какая-то идея, то ок, пусть будет так. Иногда это может стать хорошим архитектурным решением. Я отметил несколько мест, на которые стоит обратить внимание и предложил несколько вариантов рефакторинга кода. Почитай и попробуй выполнить этот рефакторинг. В основном хотелось бы поправить валидацию. Давай это исправим и двинемся дальше :)

2022-10-06 13:19 UTC, agadoev commented on .eslintignore
> +server.js
mydash и server.js так же относятся к исходному коду проекта, поэтому я не стал бы добавлять их в eslintignore, пусть линтятся

2022-10-06 13:19 UTC, agadoev commented on src/components/dialog/dialog.ts
> +    toogleSidebar: () => void;
Это свойство уже есть в IncomingProps

2022-10-06 13:19 UTC, agadoev commented on src/utils/validate.ts
> +}
Предлагаю здесь вместо enum'а воспользоваться union'ом. Почитать про их разницу можно [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

union не компилится в объект, нам не нужно создавать для каждого объекта перечисления строку

2022-10-06 13:19 UTC, agadoev commented on src/utils/validate.ts
> +): string => {
функция называется isInputValid и я ожидаю, что она вернет мне boolean, но она возвращает строку. Постарайся провести такой рефакторинг, чтобы isInputValid возвращал boolean

2022-10-06 13:19 UTC, agadoev commented on src/utils/validate.ts
> +    }
Этот функционал можно вынести в отдельную небольшую функцию, которая проверяет, является ли строка пустой. Вообще всю валидацию можно свести к набору небольших функций-валидаторов, каждая из которых проверяет что-то одно, например
```
empty = (value: string): boolean =>
email = (value: string): boolean =>
```

потом эти функции можно легко комбинировать между собой. Таким образом код будет более гибким и менее запутанным
```
if (empty(input)) {
 /* some action */
}
if (!email(input)) {
  /* some action */
}
```

и т.к. у всех таких функций-валидаторов одна и та же сигнатура, можно выделить ее в тип
```
type TValidator = (value: string) => boolean
```

в общем пространство для рефакторинга есть и я накидал вариантов

2022-10-06 13:19 UTC, agadoev commented on src/utils/got/got.ts
> +    method?: string;
Тут можно конкретизировать

```suggestion
    method?: METHOD;
```

2022-10-06 13:19 UTC, agadoev commented on src/utils/got/got.ts
> +    return out.replace(/ /g, '%20');
Решение через мутацию выглядит довольно сложным и дебажить это будет затруднительно. Я предложу более функциональное решение через комбинацию функций
```suggestion
       const stringified = Object
        .entries(data)
        .map(([key, value]) => `${key}=${value}`)
        .join('&')

    return '?' + stringified
```

2022-10-06 13:19 UTC, agadoev commented on src/utils/got/got.ts
> +class Got {
Got не очень удачное название класса, потому что оно не отражает самого главного, что есть в этом классе. А именно реализация HTTP запросов

2022-10-06 13:19 UTC, agadoev commented on src/utils/got/got.ts
> +    request = (url: string, options: Options, timeout: number = 5000) => {
timeout уже передается в options. Давай оставим либо передачу отдельно через параметры функции, либо через options. Может ввести в заблуждение

2022-10-06 13:19 UTC, agadoev commented on src/utils/validate.ts
> +            errorText = 'от 3 до 20 символов, латиница, цифры, символы:-_';
По хорошему, информация о тексте ошибок должна находиться не в компоненте валидации, а в компоненте отображения. Существует принцип единственной ответственности, по которому модуль (функция, класс, компонент, в общем архитектурная единица) должна иметь одну и только одну причину для изменения. Я хочу менять валидатор только тогда, когда меняются правила валидации. Если изменится текст ошибки (или нужно будет туда внезапно вставить ссылку),  не хочу для этого менять код валидатора. Попробуй реализовать такой рефакторинг, чтобы вынести текст ошибок в те компоненты, где инпуты используются, а валидатор пусть возвращает boolean

2022-10-06 13:19 UTC, agadoev commented on src/pages/login/login.ts
> +        console.log(formValues);
отладочные консоль логи полезны при отладке, но в проде их лучше не держать.

2022-10-06 13:30 UTC, sokol-rc commented on src/pages/login/login.ts
> +        console.log(formValues);
пункт 5 из Тз
Сделайте сбор данных из формы. В console.log должен выводиться объект со всеми заполненными полями формы.

2022-10-06 13:46 UTC, sokol-rc commented on src/pages/login/login.ts
> +        console.log(formValues);
А можно как-нибудь для ревью оставить комментарий?
я бы так и написал напротив console.log //необходимо по ТЗ
т.к. сам понимаю, что console.log на прод не нужно.

2022-10-07 01:37 UTC, sokol-rc commented
Спасибо за ревью!
Про IncomingProps и Props нет, идеи никакой не было. Думал, что так лучше, когда компонент не может принимать параметры по названию такие же, как его собственные элементы, попадающие в props вниз по компонентам.

Про console.log, так было в тз. И комментарии по тз ставить нельзя(

Благодарю за подсказку с валидацией, переписал чуть иначе, но по своему. Как мне кажется, стало лучше и чище. Пока не понимаю, где лучше хранить шаблоны регулярных выражений, положил в папку валидации. Была мысль прямо в компоненте их писать.

2022-10-07 05:32 UTC, agadoev commented on src/pages/login/login.ts
> +        console.log(formValues);
можешь в коде комментарий оставить, будет норм, ведь для этого комментарии и нужны)

2022-10-07 05:39 UTC, agadoev approved these changes
Привет, @sokol-rc 
Да, вижу правки, все ок. Держать регулярки в папке с валидацией - хорошее решение, потому что они используются только для валидации и менять их нужно будет только в том случае, если изменится правило валидации
Все ок, работу принимаю :)

2022-10-07 07:29 UTC, merged